# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import communication_pb2 as communication__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class CommunicationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendFrame = channel.unary_unary(
                '/Communication/SendFrame',
                request_serializer=communication__pb2.Frame.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetTargetFrame = channel.unary_stream(
                '/Communication/GetTargetFrame',
                request_serializer=communication__pb2.FrameNameList.SerializeToString,
                response_deserializer=communication__pb2.Frame.FromString,
                )


class CommunicationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTargetFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommunicationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.SendFrame,
                    request_deserializer=communication__pb2.Frame.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetTargetFrame': grpc.unary_stream_rpc_method_handler(
                    servicer.GetTargetFrame,
                    request_deserializer=communication__pb2.FrameNameList.FromString,
                    response_serializer=communication__pb2.Frame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Communication', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Communication(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Communication/SendFrame',
            communication__pb2.Frame.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTargetFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Communication/GetTargetFrame',
            communication__pb2.FrameNameList.SerializeToString,
            communication__pb2.Frame.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
